offline=1
no-sync=1
fixed-difficulty=1
disable-dns-checkpoints=1
out-peers=0
rpc-bind-ip=0.0.0.0
confirm-external-bind=1
restricted-rpc=1
p2p-bind-port=20260
rpc-bind-port=20261
hide-my-port=1
log-level=1
enforce-dns-checkpointing=0
